### ISSUE TITLE
QGIS 3.22.16-1 Białowieża Portable EO

### ISSUE THREAD

**Issue by 20actus** [pigreco/QGIS_portable_3x#8]
Buongiorno,
ho scaricato e installato su pendrive QGIS 3.22.16-1 Białowieża Portable EO
https://github.com/pigreco/QGIS_portable_3x
https://drive.google.com/file/d/103EBACERFZXL4IoNg3d0Q0FBaCu5sAcN/view?usp=sharing
In un primo momento non riuscivo ad installare il plugin MMQGIS, ora sembra che l’abbia installato compare nell’elenco dei plugin installati, però non compare la voce in alto nella barra dei menu.
Grazie e cordiali saluti

MESSAGGI DI LOG

Errore python: Impossibile caricare il plugin 'mmqgis' a causa di un errore chiamando il metodo classFactory() Vedi il log dei messaggi (Errore Python) per maggiori dettagli.

Errore python
2024-10-29T13:32:38     CRITICAL    Traceback (most recent call last):
              File "D:\OSGeo4W64_3.22.16-ltr_grass-saga\OSGeo4W64\qgisconfig\profiles\default/python/plugins\mmqgis\mmqgis_dialogs.py", line 29, in 
              from .mmqgis_library import *
              File "D:\OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "D:\OSGeo4W64_3.22.16-ltr_grass-saga\OSGeo4W64\qgisconfig\profiles\default/python/plugins\mmqgis\mmqgis_library.py", line 19, in 
              import ssl
              File "D:\OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "D:\OSGEO4~1.16-\OSGEO4~1\qgis\apps\Python39\lib\ssl.py", line 98, in 
              import _ssl # if we can't import it, let the error propagate
              File "D:\OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ImportError: DLL load failed while importing _ssl: Impossibile trovare il modulo specificato.
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "D:\OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "D:\OSGeo4W64_3.22.16-ltr_grass-saga\OSGeo4W64\qgisconfig\profiles\default/python/plugins\mmqgis\__init__.py", line 17, in classFactory
              from .mmqgis_menu import mmqgis_menu
              File "D:\OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "D:\OSGeo4W64_3.22.16-ltr_grass-saga\OSGeo4W64\qgisconfig\profiles\default/python/plugins\mmqgis\mmqgis_menu.py", line 19, in 
              from .mmqgis_dialogs import *
              File "D:\OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "D:\OSGeo4W64_3.22.16-ltr_grass-saga\OSGeo4W64\qgisconfig\profiles\default/python/plugins\mmqgis\mmqgis_dialogs.py", line 31, in 
              from mmqgis_library import *
              File "D:\OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'mmqgis_library'
             

2024-10-29T13:32:38     INFO    Caricato mmqgis (pacchetto: mmqgis)
2024-10-29T13:32:40     INFO    Caricato MetaSearch Catalog Client (pacchetto: MetaSearch)
2024-10-29T13:32:41     INFO    Caricato DB Manager (pacchetto: db_manager)
2024-10-29T13:32:44     INFO    Caricato GRASS GIS provider (pacchetto: grassprovider)
2024-10-29T13:32:50     INFO    Caricato Processing (pacchetto: processing)

Plugin
2024-10-29T13:32:38     INFO    Caricato mmqgis (pacchetto: mmqgis)
2024-10-29T13:32:40     INFO    Caricato MetaSearch Catalog Client (pacchetto: MetaSearch)
2024-10-29T13:32:41     INFO    Caricato DB Manager (pacchetto: db_manager)
2024-10-29T13:32:44     INFO    Caricato GRASS GIS provider (pacchetto: grassprovider)
2024-10-29T13:32:50     INFO    Caricato Processing (pacchetto: processing)

Generale
2024-10-29T13:32:50     INFO    Stato applicazione:
             QGIS_PREFIX_PATH var amb: D:/OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr
             Prefisso: D:/OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr
             Percorso del plugin: D:/OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/plugins
             Percorso pacchetto dati: D:/OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/.
             Nome tema attivo: default
             Percorso tema attivo: D:/OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./resources/themes\default\icons/
             Percorso tema predefinito: :/images/themes/default/
             Percorso di ricerca SVG: D:/OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./svg/
              D:\OSGeo4W64_3.22.16-ltr_grass-saga\OSGeo4W64\qgisconfig\profiles\default/svg/
             Percorso DB utente: D:/OSGEO4~1.16-/OSGEO4~1/qgis/apps/qgis-ltr/./resources/qgis.db
             Percorso DB Auth: D:\OSGeo4W64_3.22.16-ltr_grass-saga\OSGeo4W64\qgisconfig\profiles\default/qgis-auth.db
             
![QGIS 3 22 16-1 Białowieża Portable EO](https://github.com/user-attachments/assets/7ce822e2-8533-4cea-ad12-3eb8231439ef)

**Comment by pigreco** [comment]
ciao @20actus, perché vuoi installare questo plugin, a cosa ti serve?

**Comment by 20actus** [comment]
Salve, sto seguendo un tutorial su youtube per principianti qgis da zero (Corso QGIS ATI Tutorial 1 di 11 - Prima lezione di QGIS: scaricare e installare QGIS su windows 7o), il primo dei tutorial dice di installare il plugin mmqgis per fare delle operazioni con i layer nelle successive esercitazioni, grazie cordiali saluti

**Comment by pigreco** [comment]
Ciao @20actus altra domanda, perché usi QGIS 3.22.16 e non una più recente?

Ho fatto un test rapido e l'errore c'è anche da me.

**Comment by 20actus** [comment]
Salve pigreco, perché  lo studio con cui dovrò collaborare utilizza QGIS 3.22.16. Grazie e cordiali saluti

**Comment by pigreco** [comment]
@agiudiceandrea secondo te è possibile risolvere il problema?

**Comment by agiudiceandrea** [comment]
@pigreco, l'errore si verifica anche utilizzando QGIS 3.22.16 installato normalmente tramite gli installer OSGeo4W? L'errore si verifica anche utilizzando una versione più recente di QGIS "portable"?

**Comment by pigreco** [comment]
@agiudiceandrea 
> L'errore si verifica anche utilizzando una versione più recente di QGIS "portable"?

no, ho appena provato con la Portable QGIS 3.34.10, l'installazione del plugin va a buon fine.

> l'errore si verifica anche utilizzando QGIS 3.22.16 installato normalmente tramite gli installer OSGeo4W?

purtroppo non posso testarlo

**Comment by agiudiceandrea** [comment]
@pigreco le versioni "portatili" create da te decomprimendo tutti i file presenti nell'installer OSGeo4W e modificando il file .bat di esecuzione di QGIS purtroppo, ovviamente, non effettuano tutte le procure di post-installazione previste dallo stesso installer OSGeo4W. La modifica del file .bat di esecuzione di QGIS è un "hack" per permettere a QGIS di avviarsi e "semplicemente" di funzionare in gran parte delle situazioni.

Per esempio, fra le procedure di post-installazione c'è quella relativa all'aggiornamento del database dei CRS, alla corretta impostazione di variabili d'ambiente, di vari moduli Python, ecc...

In questo caso dovrebbe essere sufficiente copiare i file `\bin\libcrypto-1_1-x64.dll` e `\bin\libssl-1_1-x64.dll` rispettivamente come `\apps\Python39\DLLs\libcrypto-1_1.dll` e `\apps\Python39\DLLs\libssl-1_1.dll`.

**Comment by pigreco** [comment]
> In questo caso dovrebbe essere sufficiente copiare i file `\bin\libcrypto-1_1-x64.dll` e `\bin\libssl-1_1-x64.dll` rispettivamente come `\apps\Python39\DLLs\libcrypto-1_1.dll` e `\apps\Python39\DLLs\libssl-1_1.dll`.

probabilmente ho capito male, ma non funziona.
Ho copiato questi due file `\bin\libcrypto-1_1-x64.dll` e `\bin\libssl-1_1-x64.dll` dentro la cartella del plugin `\apps\Python39\DLLs\libcrypto-1_1.dll` e `\apps\Python39\DLLs\libssl-1_1.dll`, ma non funziona.

**Comment by agiudiceandrea** [comment]
> > In questo caso dovrebbe essere sufficiente copiare i file `\bin\libcrypto-1_1-x64.dll` e `\bin\libssl-1_1-x64.dll` rispettivamente come `\apps\Python39\DLLs\libcrypto-1_1.dll` e `\apps\Python39\DLLs\libssl-1_1.dll`.
> 
> probabilmente ho capito male, ma non funziona. Ho copiato questi due file `\bin\libcrypto-1_1-x64.dll` e `\bin\libssl-1_1-x64.dll` dentro la cartella del plugin `\apps\Python39\DLLs\libcrypto-1_1.dll` e `\apps\Python39\DLLs\libssl-1_1.dll`, ma non funziona.

Non nella carella del plugin, ma nella cartella di QGIS portatile.

**Comment by pigreco** [comment]
> Non nella carella del plugin, ma nella cartella di QGIS portatile.

qui li ho messi
![image](https://github.com/user-attachments/assets/7f615889-0d1a-4dce-9499-0928b30d7b0b)

**Comment by agiudiceandrea** [comment]
Il nome dei file deve essere libcrypto-1_1.dll e libssl-1_1.dll

**Comment by pigreco** [comment]
@agiudiceandrea 
perfetto, funziona! Grazie
![image](https://github.com/user-attachments/assets/875f3afd-7529-4755-a176-577c1ebaae80)

@20actus 
Copia questi due file `\bin\libcrypto-1_1-x64.dll` e `\bin\libssl-1_1-x64.dll` dentro la cartella della Portable in 
 `\apps\Python39\DLLs\libcrypto-1_1.dll` e `\apps\Python39\DLLs\libssl-1_1.dll`, rinomina i file eliminando `-x64`

**Comment by 20actus** [comment]
Salve, @pigreco, @agiudiceandrea,
eseguito come da vostre istruzioni, funziona, grazie molte per la disponibilitò e le indicazioni. Cordiali saluti
